### ISSUE TITLE
Console UI fail randomly - credentials list not refreshed

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/console#1266]
**Description**

Instances UI has an issue with web sockets. Occasionally, the list of credentials and bound applications are not updated after item creation (binding or new credential), causing the UI test to fail. 

```
  ● Catalog basic tests › Check credentials

    TimeoutError: waiting for selector "[data-e2e-id="credential-name"]" failed: timeout 30000ms exceeded

      513 |     await catalog.createCredentials(page, additionalData);
      514 | 
    > 515 |     await frame.waitForSelector(credentialName);
          |                 ^
      516 |     const allCredentials = await catalog.getCredentials(frame);
      517 |     expect(allCredentials.length).toEqual(1);
      518 | 

      at new WaitTask (node_modules/puppeteer/lib/DOMWorld.js:561:28)
      at DOMWorld._waitForSelectorOrXPath (node_modules/puppeteer/lib/DOMWorld.js:490:22)
      at DOMWorld.waitForSelector (node_modules/puppeteer/lib/DOMWorld.js:444:17)
      at Frame.waitForSelector (node_modules/puppeteer/lib/FrameManager.js:628:47)
      at Frame.<anonymous> (node_modules/puppeteer/lib/helper.js:112:23)
      at waitForSelector (src/tests/catalog-ui-test.js:515:17)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:114:21)
      at step (src/tests/catalog-ui-test.js:39:191)
      at src/tests/catalog-ui-test.js:39:361
```

**Attachments**
<img width="1354" alt="Screen Shot 2019-09-18 at 11 17 33" src="https://user-images.githubusercontent.com/6783567/65135307-ff094500-da05-11e9-95a0-fdf575038295.png">

**Comment by kwiatekus** [comment]
Still failing
