### ISSUE TITLE
 `Expose API for Service` test fails randomly

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/console#1272]
**Description**

Console basic tests failing - 404 for `test-expose-api` namespace

```
  ● Console basic tests › Expose API for Service

    thrown: Object {
      "body": Object {
        "apiVersion": "v1",
        "code": 404,
        "details": Object {
          "kind": "namespaces",
          "name": "test-expose-api",
        },
        "kind": "Status",
        "message": "namespaces \"test-expose-api\" not found",
        "metadata": Object {},
        "reason": "NotFound",
        "status": "Failure",
      },
      "response": Object {
        "body": [Object],
        "headers": [Object],
        "request": [Object],
        "statusCode": 404,
      },
    }

    Error: 

      84 |   });
      85 | 
    > 86 |   test('Expose API for Service', async () => {
         |   ^
      87 |     const apiName = 'ui-test-exposed-api';
      88 |     let frame, exposedApiCellTexts, serviceUrl, service;
      89 | 

      at Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:85:20)
      at Suite.test (src/tests/console-basic-test.js:86:3)
      at describe (src/utils/skip.js:7:5)
      at Object.<anonymous> (src/tests/console-basic-test.js:22:1)
```

**Comment by kwiatekus** [comment]
Please have a look how test namespace is created in catalog-ui test. Such problems never occurred in that test.
