### ISSUE TITLE
Stabilize UI tests

### ISSUE THREAD

**Issue by akucharska** [kyma-project/console#338]
**Description**

UI tests are sometimes failing due to:
- net::ERR_NETWORK_CHANGED - this is probably a problem with k8s configuration
- timeouts
- waiting for selector - this might be due to the instability of cluster itself.

When cluster with stability-checker is running for a longer period of tile tests are more likely to fail

**Expected result**

More stable tests

**Actual result**

Tests are failing randomly

**Steps to reproduce**

Launch stability checker on cluster

**Troubleshooting**

More logs:

```
Testing 'test-core-core-ui-acceptance'
'test-core-core-ui-acceptance' failed due to too long Pending status
Fetching events from 'test-core-core-ui-acceptance':
End of testing 'test-core-core-ui-acceptance'
```

———————————

```
Catalog basic tests › Check service class list

    TimeoutError: Timed out after 30000 ms while trying to connect to Chrome! The only Chrome revision guaranteed to work is r599821

      at onTimeout (node_modules/puppeteer/lib/Launcher.js:353:14)
      at Timeout.callback (node_modules/jsdom/lib/jsdom/browser/Window.js:678:19)
```

———————————

  ```
net::ERR_NETWORK_CHANGED at https://console.wookiee.cluster.kyma.cx
      19 |   const height = config.viewportHeight;
      20 |   await page.setViewport({ width, height });
    > 21 |   await page.goto(consoleUrl, { waitUntil: 'networkidle0' });
         |              ^
      22 |   await waitForNavigationAndContext(page);
      23 | 
      24 |   return { page, browser };
```

———————————

```
Catalog basic tests › Check instances list

    TimeoutError: waiting for selector "[data-e2e-id="toolbar-headline"]" failed: timeout 30000ms exceeded

      204 | 
      205 |     const frame = await kymaConsole.getFrame(page);
    > 206 |     await frame.waitForSelector(instancesHeaderSelector);
          |                 ^
      207 |     const instancesHeader = await frame.$eval(
      208 |       instancesHeaderSelector,
      209 |       item => item.innerHTML

      at new WaitTask (node_modules/puppeteer/lib/FrameManager.js:955:28)
      at Frame._waitForSelectorOrXPath (node_modules/puppeteer/lib/FrameManager.js:846:12)
      at Frame.waitForSelector (node_modules/puppeteer/lib/FrameManager.js:804:17)
      at waitForSelector (src/tests/catalog-ui-test.js:206:17)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:114:21)
      at step (src/tests/catalog-ui-test.js:43:191)
      at src/tests/catalog-ui-test.js:43:361
```

————————————
x2

```
TimeoutError: waiting for selector "[data-e2e-id="service-title"]" failed: timeout 30000ms exceeded

      145 | 
      146 |     const frame2 = await kymaConsole.getFrame(page);
    > 147 |     await frame2.waitForSelector(exampleServiceClassTitle);
          |                  ^
      148 |     const title = await frame2.$(exampleServiceClassTitle);
      149 |     const provider = await frame2.$(exampleServiceClassProvider);
      150 |     const description = await frame2.$(exampleServiceClassDescription);

      at new WaitTask (node_modules/puppeteer/lib/FrameManager.js:955:28)
      at Frame._waitForSelectorOrXPath (node_modules/puppeteer/lib/FrameManager.js:846:12)
      at Frame.waitForSelector (node_modules/puppeteer/lib/FrameManager.js:804:17)
      at waitForSelector (src/tests/catalog-ui-test.js:147:18)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:114:21)
      at step (src/tests/catalog-ui-test.js:43:191)
      at src/tests/catalog-ui-test.js:43:361
```

———————————————
x3

```
Catalog basic tests › Check service class list

    TimeoutError: waiting for selector ".sf-modal.sf-modal--min" to be hidden failed: timeout 30000ms exceeded

      85 |   await page.type(envNameInput, name);
      86 |   await page.click(createBtn);
    > 87 |   await page.waitForSelector(createEnvModal, { hidden: true });
         |              ^
      88 |   await page.reload({ waitUntil: 'networkidle0' });
      89 |   await waitForNavigationAndContext(page);
      90 | 

      at new WaitTask (node_modules/puppeteer/lib/FrameManager.js:955:28)
      at Frame._waitForSelectorOrXPath (node_modules/puppeteer/lib/FrameManager.js:846:12)
      at Frame.waitForSelector (node_modules/puppeteer/lib/FrameManager.js:804:17)
      at Page.waitForSelector (node_modules/puppeteer/lib/Page.js:990:29)
      at Object.waitForSelector (src/commands/console.js:87:14)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:114:21)
      at step (src/commands/console.js:468:191)
      at src/commands/console.js:468:361
```

——————————————
x2

```
 TimeoutError: waiting for selector ".sf-header" failed: timeout 30000ms exceeded

      14 | async function login(page, config) {
      15 |   await _loginViaDex(page, config);
    > 16 |   return await page.waitForSelector('.sf-header');
         |                     ^
      17 | }
      18 | 
      19 | async function getFrame(page) {

      at new WaitTask (node_modules/puppeteer/lib/FrameManager.js:955:28)
      at Frame._waitForSelectorOrXPath (node_modules/puppeteer/lib/FrameManager.js:846:12)
      at Frame.waitForSelector (node_modules/puppeteer/lib/FrameManager.js:804:17)
      at Page.waitForSelector (node_modules/puppeteer/lib/Page.js:990:29)
      at Object.waitForSelector (src/commands/console.js:16:21)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:114:21)
      at step (src/commands/console.js:468:191)
      at src/commands/console.js:468:361
```

————————————

```
Console basic tests › Go to details and back

    expect(string).toContain(value)

    Expected string:
      "← Back to Environment
    General Settings
    INTEGRATION
    Remote Environments
    Service Brokers
    IDP Presets
    ADMINISTRATION
    Global Permissions
    DIAGNOSTICS
    Stats & Metrics
    Tracing
    Docs
    Remote Environments
    / testenvironment
    Connect Remote Environment
    Error
    Http failure response for (unknown url): 0 Unknown Error
    OK"
    To contain value:
      "General Information"

      116 |     const detailsText = await page.evaluate(() => document.body.innerText);
      117 |     expect(detailsText).toContain(config.testEnv);
    > 118 |     expect(detailsText).toContain('General Information');
          |                         ^
      119 |     await kymaConsole.openLink(page, 'a', 'Remote Environments');
      120 |     const listText = await page.evaluate(() => document.body.innerText);
      121 |     expect(listText).toContain(config.testEnv);

      at toContain (src/tests/console-basic-test.js:118:25)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:114:21)
      at step (src/tests/console-basic-test.js:31:191)
      at src/tests/console-basic-test.js:31:361
```

——————————
```
Console basic tests › Check if remote environment exist

    expect(array).not.toContain(value)

    Expected array:
      ["ec-default", "hmc-default", "testenvironment"]
    Not to contain value:
      "testenvironment"

       96 |     const remoteEnvironments = await kymaConsole.getRemoteEnvironments(page);
       97 |     console.log('Check if remote environment exists', remoteEnvironments);
    >  98 |     expect(remoteEnvironments).not.toContain(config.testEnv);
          |                                    ^
       99 |   });
      100 | 
      101 |   test('Create remote environment', async () => {

      at toContain (src/tests/console-basic-test.js:98:36)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:114:21)
      at step (src/tests/console-basic-test.js:31:191)
      at src/tests/console-basic-test.js:31:361
```

————————

```
console.log src/utils/testIfWebResourceAvailable.js:16
      Testing avilibility of https://dex.wookiee.cluster.kyma.cx/.well-known/openid-configuration : 200
    console.log src/commands/console.js:7
      Trying to log in admin@kyma.cx via dex
    console.log src/tests/console-basic-test.js:44
      Check if envs exist [ '+ Create Environment', 'production', 'qa', 'stage' ]
    console.log src/tests/console-basic-test.js:86
      Delete env - exist envs [ '+ Create Environment',
        'production',
        'qa',
        'stage',
        'testenvironment' ]
    console.log src/tests/console-basic-test.js:87
      Delete env - envs after deletion [ '+ Create Environment', 'production', 'qa', 'stage' ]
    console.log src/tests/console-basic-test.js:97
      Check if remote environment exists [ 'ec-default', 'hmc-default', 'test-remote-env' ]
    console.log src/tests/console-basic-test.js:106
      Create new remote environment, remote envs:  [ 'ec-default',
        'hmc-default',
        'test-remote-env',
        'testenvironment' ]
    console.log src/utils/logging.js:29
      Request POST https://ui-api.wookiee.cluster.kyma.cx/graphql failed with message : net::ERR_ABORTED
    console.log src/utils/logging.js:29
      Request POST https://ui-api.wookiee.cluster.kyma.cx/graphql failed with message : net::ERR_NETWORK_CHANGED
    console.log src/utils/logging.js:29
      Request POST https://ui-api.wookiee.cluster.kyma.cx/graphql failed with message : net::ERR_NETWORK_CHANGED
    console.log src/commands/console.js:51
      Removing testenvironment environment
```

————————
Console

```
    console.log src/utils/testIfWebResourceAvailable.js:16
      Testing avilibility of https://dex.wookiee.cluster.kyma.cx/.well-known/openid-configuration : 200
    console.log src/commands/console.js:7
      Trying to log in admin@kyma.cx via dex
    console.log src/utils/logging.js:29
      Request GET https://catalog.wookiee.cluster.kyma.cx/static/js/main.73280792.js failed with message : net::ERR_ABORTED
    console.log src/utils/logging.js:29
      Request GET https://catalog.wookiee.cluster.kyma.cx/config/config.js failed with message : net::ERR_ABORTED
    console.log src/utils/logging.js:29
      Request GET https://catalog.wookiee.cluster.kyma.cx/swagger-ui.css failed with message : net::ERR_ABORTED
    console.log src/utils/logging.js:29
      Request GET https://catalog.wookiee.cluster.kyma.cx/reset.css failed with message : net::ERR_ABORTED
    console.log src/utils/logging.js:29
      Request GET https://catalog.wookiee.cluster.kyma.cx/static/css/main.5b6a532c.css failed with message : net::ERR_ABORTED
```

**Comment by derberg** [comment]
It is fixed in other issue, so far so stable
