### ISSUE TITLE
UI tests fails due to "net::ERR_ABORTED"

### ISSUE THREAD

**Issue by mjasinski5** [kyma-project/console#451]
During stability checks, UI-tests fails regularly with following errors:

```
FAIL src/tests/catalog-ui-test.js (132.185s)
  ● Console

    console.log src/utils/testIfWebResourceAvailable.js:16
      Testing avilibility of https://dex.nightly.cluster.kyma.cx/.well-known/openid-configuration : 200
    console.log src/commands/console.js:7
      Trying to log in admin@kyma.cx via dex
    console.log src/utils/logging.js:29
      Request GET https://catalog.nightly.cluster.kyma.cx/static/js/main.668ea895.js failed with message : net::ERR_ABORTED
    console.log src/utils/logging.js:29
      Request POST https://ui-api.nightly.cluster.kyma.cx/graphql failed with message : net::ERR_ABORTED
    console.log src/commands/console.js:75
      Removing catalogtestenvironment environment

  ● Catalog basic tests › Check instances list

    expect(array).toContain(value)

    Expected array:
      ["test-redis-instance2"]
    To contain value:
      "test-redis-instance"

      218 |     await catalog.feelInInput(frame, exampleInstanceName, 'search');
      219 |     const searchedInstances = await catalog.getInstances(frame);
    > 220 |     expect(searchedInstances).toContain(exampleInstanceName);
          |                               ^
      221 |
      222 |     await catalog.feelInInput(frame, searchBySth, 'search');
      223 |     const newSearchedInstances = await catalog.getInstances(frame);

      at toContain (src/tests/catalog-ui-test.js:220:31)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:114:21)
      at step (src/tests/catalog-ui-test.js:43:191)
      at src/tests/catalog-ui-test.js:43:361

  ● Catalog basic tests › Check details

    TimeoutError: waiting for selector "[data-e2e-id="instance-name-test-redis-instance"]" failed: timeout 30000ms exceeded

      254 |
      255 |     const frame = await kymaConsole.getFrame(page);
    > 256 |     const redis = await frame.waitForSelector(exampleInstanceLink, {
          |                               ^
      257 |       visible: true
      258 |     });
      259 |     await redis.click();

      at new WaitTask (node_modules/puppeteer/lib/FrameManager.js:955:28)
      at Frame._waitForSelectorOrXPath (node_modules/puppeteer/lib/FrameManager.js:846:12)
      at Frame.waitForSelector (node_modules/puppeteer/lib/FrameManager.js:804:17)
      at waitForSelector (src/tests/catalog-ui-test.js:256:31)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:114:21)
      at step (src/tests/catalog-ui-test.js:43:191)
      at src/tests/catalog-ui-test.js:43:361

PASS src/tests/console-basic-test.js (72.295s)
  ● Console

    console.log src/utils/testIfWebResourceAvailable.js:16
      Testing avilibility of https://dex.nightly.cluster.kyma.cx/.well-known/openid-configuration : 200
    console.log src/commands/console.js:7
      Trying to log in admin@kyma.cx via dex
    console.log src/tests/console-basic-test.js:44
      Check if envs exist [ '+ Create Namespace', 'production', 'qa', 'stage' ]
    console.log src/tests/console-basic-test.js:88
      Delete env - exist envs [ '+ Create Namespace',
        'production',
        'qa',
        'stage',
        'testenvironment' ]
    console.log src/tests/console-basic-test.js:89
      Delete env - envs after deletion [ '+ Create Namespace', 'production', 'qa', 'stage' ]
    console.log src/tests/console-basic-test.js:99
      Check if Application exists []
    console.log src/tests/console-basic-test.js:108
      Create new Application, remote envs:  [ 'testenvironment' ]
    console.log src/commands/common.js:42
      Retrying... Attempt No. 1 of 3
    console.log src/utils/logging.js:29
      Request DELETE https://apiserver.nightly.cluster.kyma.cx/apis/applicationconnector.kyma-project.io/v1alpha1/applications/testenvironment failed with message : net::ERR_ABORTED
    console.log src/commands/console.js:157
      Applications was updated
    console.log src/tests/console-basic-test.js:139
      Delete Application, remaining remote envs:  []
    console.log src/commands/console.js:75
      Removing testenvironment environment

PASS src/tests/docs-ui-test.js (28.167s)
  ● Console

    console.log src/utils/testIfWebResourceAvailable.js:16
      Testing avilibility of https://dex.nightly.cluster.kyma.cx/.well-known/openid-configuration : 200
    console.log src/commands/console.js:7
      Trying to log in admin@kyma.cx via dex


Test Suites: 1 failed, 2 passed, 3 total
Tests:       2 failed, 14 passed, 16 total
Snapshots:   0 total
Time:        235.499s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ui-tests@0.1.3 test:cluster: `jest -i --forceExit --detectOpenHandles`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ui-tests@0.1.3 test:cluster script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-01-07T03_46_33_536Z-debug.log
```

**Comment by mjasinski5** [comment]
https://github.com/kyma-project/console/issues/456

**Comment by mjasinski5** [comment]
Issue has been resolved.
