### ISSUE TITLE
Initialisation of UI Acceptance Tests sometimes failing

### ISSUE THREAD

**Issue by michal-hudy** [kyma-project/console#691]
**Description**

UI Acceptance tests sometimes failing during initialization of the environment.

```
FAIL src/tests/catalog-ui-test.js (210.601s)
  ● Console

    console.log jest-setup.js:3
      Setting default timeout to 240 seconds
    console.log src/setup/test-bundle-installer.js:17
      Installing test bundle...
    console.log src/setup/namespace-manager.js:17
      Creating namespace service-catalog-ui-test...
    console.log src/setup/helm-broker/configurer.js:12
      Including test bundle repository for Helm Broker...
    console.log src/setup/helm-broker/configurer.js:53
      Waiting for ready test bundle...
    console.log src/setup/helm-broker/configurer.js:63
      Test bundle is available.
    console.log src/setup/helm-broker/configurer.js:32
      Waiting for ready minimal plan...
    console.log src/setup/helm-broker/configurer.js:42
      Minimal plan is available.
    console.error node_modules/jest-jasmine2/build/jasmine/Env.js:157
      Unhandled error
    console.error node_modules/jest-jasmine2/build/jasmine/Env.js:158
      SyntaxError: Unexpected end of JSON input
          at JSON.parse (<anonymous>)
          at LineStream.stream.on (/app/node_modules/@kubernetes/client-node/dist/watch.js:42:28)
          at emitOne (events.js:116:13)
          at LineStream.emit (events.js:211:7)
          at addChunk (_stream_readable.js:263:12)
          at readableAddChunk (_stream_readable.js:250:11)
          at LineStream.Readable.push (_stream_readable.js:208:10)
          at LineStream.Transform.push (_stream_transform.js:147:32)
          at LineStream.Object.<anonymous>.LineStream._pushBuffer (/app/node_modules/byline/lib/byline.js:126:17)
          at LineStream.Object.<anonymous>.LineStream._flush (/app/node_modules/byline/lib/byline.js:140:8)
          at LineStream.prefinish (_stream_transform.js:137:10)
          at emitNone (events.js:106:13)
          at LineStream.emit (events.js:208:7)
          at prefinish (_stream_writable.js:602:14)
          at finishMaybe (_stream_writable.js:610:5)
          at endWritable (_stream_writable.js:621:3)
          at LineStream.Writable.end (_stream_writable.js:572:5)
          at Request.onend (internal/streams/legacy.js:44:10)
          at emitOne (events.js:121:20)
          at Request.emit (events.js:211:7)
          at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:1083:12)
          at Object.onceWrapper (events.js:313:30)
          at emitNone (events.js:111:20)
          at IncomingMessage.emit (events.js:208:7)
          at endReadableNT (_stream_readable.js:1064:12)
          at _combinedTickCallback (internal/process/next_tick.js:139:11)
          at process._tickCallback (internal/process/next_tick.js:181:9)
    console.log src/commands/common.js:51
      Opening https://console.gkeint-commit-a467be6e-yxzc29s4ys.build.kyma-project.io
    console.log src/commands/console.js:14
      Trying to log in admin@kyma.cx via dex
    console.log src/commands/common.js:17
      Request failed:
      URL: https://ui-api.gkeint-commit-a467be6e-yxzc29s4ys.build.kyma-project.io/graphql 
      Method: OPTIONS
      Failure: net::ERR_ABORTED
    console.log src/utils/logging.js:36
      Request OPTIONS https://ui-api.gkeint-commit-a467be6e-yxzc29s4ys.build.kyma-project.io/graphql failed with message : net::ERR_ABORTED
    console.log src/commands/common.js:17
      Request failed:
      URL: https://apiserver.gkeint-commit-a467be6e-yxzc29s4ys.build.kyma-project.io/apis/authorization.k8s.io/v1/selfsubjectrulesreviews 
      Method: POST
      Failure: net::ERR_ABORTED
    console.log src/utils/logging.js:36
      Request POST https://apiserver.gkeint-commit-a467be6e-yxzc29s4ys.build.kyma-project.io/apis/authorization.k8s.io/v1/selfsubjectrulesreviews failed with message : net::ERR_ABORTED
    console.log src/tests/catalog-ui-test.js:107
      Check if `Testing bundle` is on the list
    console.log src/tests/catalog-ui-test.js:188
      Provision `Testing bundle` with `Minimal` plan
    console.log src/tests/catalog-ui-test.js:196
      Click on the provision confirmation link and confirm you were redirected to instance details page directly
    console.log src/utils/logging.js:36
      Request GET https://instances.gkeint-commit-a467be6e-yxzc29s4ys.build.kyma-project.io/details/testing-bundle-minimal-instance failed with message : net::ERR_ABORTED
    console.log src/tests/catalog-ui-test.js:220
      Go to main Instances list view and click `Add Instance` link and confirm you went to catalog
    console.log src/utils/logging.js:36
      Request GET https://catalog.gkeint-commit-a467be6e-yxzc29s4ys.build.kyma-project.io/swagger-ui.css failed with message : net::ERR_ABORTED
    console.log src/tests/catalog-ui-test.js:258
      Confirm that indicator of provisioned instances shows 1
    console.log src/tests/catalog-ui-test.js:305
      Provision `Testing bundle` with `Full` plan
    console.log src/tests/catalog-ui-test.js:318
      Navigate manually to instances list
    console.log src/tests/catalog-ui-test.js:345
      Validate instances list
    console.log src/tests/catalog-ui-test.js:387
      Go to details of instance created with `minimal` plan
    console.log src/tests/catalog-ui-test.js:413
      Confirm all necessary fields
    console.log src/tests/catalog-ui-test.js:445
      Go to details of instance created with `full` plan
    console.log src/tests/catalog-ui-test.js:474
      Confirm all necessary fields
    console.log src/tests/catalog-ui-test.js:514
      Go to Credentials tab and create credentials and fill in the schema form
    console.log src/tests/catalog-ui-test.js:561
      Go to Bound Applications tab and confirm that in Credentials tab you see (1)
    console.log src/commands/catalog.js:194
      Confirm modal function failed
    console.log src/setup/test-bundle-installer.js:25
      Cleaning up test bundle...
    console.log src/setup/helm-broker/configurer.js:24
      Excluding test bundle repository for Helm Broker...
    console.log src/setup/namespace-manager.js:28
      Deleting namespace service-catalog-ui-test...
```

https://storage.googleapis.com/kyma-prow-logs/logs/post-master-kyma-gke-integration/1106106137121394689/build-log.txt

**Expected result**

Tests are stable and in case of fail provide clear information about problems.

**Actual result**

Tests sometimes failing and we don't know why.

**Steps to reproduce**

Execute tests many times on cluster.

**Troubleshooting**

**Comment by dariadomagala** [comment]
Catalog UI tests randomly failing https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-upgrade/1110425261410619392

**Comment by jesusreal** [comment]
@Swieca, Malgorzata logs show catalog-ui tests are failing, could you please take a look?

**Comment by jesusreal** [comment]
In case I see those tests failing today I will write here, as I am monitoring builds for today.
